# Generated by Django 6.0.1 on 2026-03-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_electorgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectorGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('elector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.elector')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.electorgroup')),
            ],
            options={
                'unique_together': {('elector', 'group')},
            },
        ),
    ]
